kanji_id = "293"
word_id = "490"

pos_tag_translations = {
        "名詞": "noun",
        "一般": "general",
        "助詞": "particle",
        "格助詞": "case-marking particle",
        "動詞": "verb",
        "自立": "independent",
        "助動詞": "auxilary verb",
        "記号": "symbol",
        "句点": "period",
        "代名詞": "pronoun",
        "係助詞": "binding particle",
        "数": "number",
        "接尾": "suffix",
        "助数詞": "counter",
        "副助詞": "adverbial particle",
        "形容動詞語幹": "adjectival noun stem",
        "固有名詞": "proper noun",
        "人名": "persons name",
        "名": "name",
        "サ変接続": "connecting irregular conjugation",
        "副詞可能": "adverb maybe",
        "副詞": "adverb",
        "助詞類接続": "particle connection",
        "形容詞": "i-adjective",
        "読点": "comma",
        "並立助詞": "listing particle",
        "副助詞": "adverbial particle",
        "並立助詞": "paralell marker",
        "終助詞": "sentence ending particle",
        "地域": "area",
        "国": "country",
        "接続助詞": "conjunction particle",
        "非自立": "not independent",
        "連体化": "pronormial particle",
        "副助詞／並立助詞／終助詞": "paralell/adverbial/listing particle",
        "連体詞": "adnomial",
        "接続詞": "conjunction",
        "接頭詞": "prefix",
        "名詞接続": "prefix + noun",
        "姓": "surname"
    }

pos_tag_encodings = {
        "noun": 1,
        "general": 2,
        "particle": 3,
        "case-marking particle": 4,
        "verb": 5,
        "independent": 6,
        "auxilary verb": 7,
        "symbol": 8,
        "period": 9,
        "pronoun": 10,
        "binding particle": 11,
        "number": 12,
        "suffix": 13,
        "counter": 14,
        "adverbial particle": 15,
        "adjectival noun stem": 16,
        "proper noun": 17,
        "persons name": 18,
        "name": 19,
        "connecting irregular conjugation": 20,
        "adverb maybe": 21,
        "adverb": 22,
        "particle connection": 23,
        "i-adjective": 24,
        "u-verb": 25,
        "ru-verb": 26,
        "exception": 27,
        "comma": 28,
        "listing particle": 29,
        "paralell marker": 31,
        "sentence ending particle": 32,
        "area": 33,
        "country": 34,
        "conjunction particle": 35,
        "not independent": 36,
        "pronormial particle": 37,
        "paralell/adverbial/listing particle": 38,
        "adnomial": 39,
        "conjunction": 40,
        "prefix": 41,
        "prefix + noun": 42,
        "surname": 43,
    }

grammars = {
   "declaring using だ":45480,
   "Negative state of being":45481,
   "Past state of being":45482,
   "Past negative":45575,
   "The は topic particle":45484,
   "The も inclusive topic particle":45485,
   "The が identifier particle":45486,
   "na-adjectives/conjugation":45538,
   "i-adjectives/conjugation":45539,
   "adjectives/exception":45540,
   "negative verbs/ru-verbs":45548,
   "negative verbs/u-verbs ending in u":45549,
   "negative verbs/u-verbs":45550,
   "negative verbs/exception":45551,
   "past tense/ru-verbs":45552,
   "past tense/す ending":45553,
   "past tense/く, ぐ ending":45554,
   "past tense/む, ぶ, ぬ ending":45555,
   "past tense/る, つ, う ending":45556,
   "The direct object を particle":45511,
   "The target に particle":45512,
   "The directional へ particle":45513,
   "The contextual で particle":45514,
   "When location is the topic":45516,
   "state-of-being clause as adjective":45519,
   "verb clause as adjective":45519,
   "the inclusive と particle":45523,
   "the vauge listing や and とか particles":45524,
   "the の particle":45525,
   "the の particle/omitting modified noun":45525,
   "the の particle/explanation":45527,
   "i-adverb":45529,
   "na-adverb":45530,
   "よ sentence ending":45533,
   "ね sentence ending":45532,
   "よね sentence ending":45534,
   "using masu": 45568,
   "using desu": 45569,
   "question ka": 45570,
    "te form positive": 45581,
    "te form negative": 45582,
    "kara": 45585
}

